version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/8000' || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

  zoo-app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APP_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "8080:8080"
    depends_on:
      dynamodb-local:
        condition: service_healthy
