app:
  dynamodb:
    endpoint: ${APP_DYNAMODB_ENDPOINT:http://dynamodb-local:8000}
    use-default-credentials: true
  cache:
    type: redis
aws:
  dynamodb:
    createTablesOnStartup: false
spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
