apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-local
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      automountServiceAccountToken: false
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:2.3.0
          args: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
spec:
  selector:
    app: dynamodb-local
  ports:
    - port: 8000
      targetPort: 8000
